### ISSUE TITLE
null block allowed in overriding member of type

### ISSUE THREAD

**Issue by JoopBL** [felipebz/zpa#116]
release 2.3.0

when overriding a member procedure it is allowed to have a null block if this block is the only block in the member. This was not reported as an issue in version 2.2.0

Example:
`  overriding member procedure p_x
   ( p_y in varchar2
   )
   as
   begin
    null;
  end;`

**Comment by felipebz** [comment]
Hi @JoopBL.

I looked at the utPLSQL code and I found the same issue reported incorrectly: https://sonarcloud.io/project/issues?id=utPLSQL-zpa-demo&issues=AWpXBnAYyRjJygCrdnJ2&open=AWpXBnAYyRjJygCrdnJ2

I agree that it's a false positive.

Thanks!
