### ISSUE TITLE
How can I configurate built-in rules?

### ISSUE THREAD

**Issue by kga676** [felipebz/zpa#119]
My questions are:
1) How can I disable some built-in rules?
2) How can can I mark bug like 'Yes it really must be like this. Do not mark this as an error in future'?

**Comment by felipebz** [comment]
Hi!

These settings are configured on the SonarQube server.
 
> 1. How can I disable some built-in rules?

First, we need to create a copy of the default quality profile:

- In your SonarQube server you can go to the "Quality Profiles" page , find the "PL/SQL (ZPA)" section and open the "Sonar way" profile (or just open http://my_sonar_server:9000/profiles/show?language=plsqlopen&name=Sonar+way).

- Open the "clog" menu (at the right) and click on "Copy"

![](https://user-images.githubusercontent.com/13829/59138622-87d30800-8964-11e9-82ca-7fd4066d2364.png)

- Give a name to the new quality profle:

![](https://user-images.githubusercontent.com/13829/59138641-a933f400-8964-11e9-8d8d-e02ceb2c61a6.png)

- The page will be reloaded with the new profile. In the "Rules" section you can click on the number of rules:

![](https://user-images.githubusercontent.com/13829/59138663-c799ef80-8964-11e9-8f35-eac754c80703.png)

Then you'll be able to deactivate any rule you want.

![](https://user-images.githubusercontent.com/13829/59138681-dc768300-8964-11e9-95a2-c8e242d13f47.png)

You can return to the previous page (your quality profile) and set it as default using the "clog" menu.

![](https://user-images.githubusercontent.com/13829/59138802-8c4bf080-8965-11e9-8898-b8154f51bdaa.png)

-------------------------

> How can can I mark bug like 'Yes it really must be like this. Do not mark this as an error in future'?

Click on the issue status and select "Resolve as won't fix".

![](https://user-images.githubusercontent.com/13829/59138727-1051a880-8965-11e9-8d7c-8228e8c8f8a5.png)

I hope this helps. :smile:

**Comment by kga676** [comment]
Thanks a lot for your answer!
