### ISSUE TITLE
False positive Specify the columns in this INSERT.

### ISSUE THREAD

**Issue by Coding-Hen** [felipebz/zpa#127]
Having a select statement after an insert throws a false positive on the insert.

We had the insert statment written as 
insert into table
select id from othertable where id = 1;

I believe that having it on the line below cased a false positive.

**Comment by felipebz** [comment]
Hi @Coding-Hen.

Your insert statement will execute successfully only if the table has a single column. When someone adds a new column, even if it's a nullable column, the insert will stop working and it'll cause a compilation error.

This problem could be avoided specifying the column in the insert, e.g.:

```
insert into table (id)
select id from othertable where id = 1;
```
