### ISSUE TITLE
Handle exceptions of this query (bulk collect into)

### ISSUE THREAD

**Issue by edbka** [felipebz/zpa#128]
Hello,
version: 2.3.0 detected "Handle exceptions of this query"

```sql
-- declared variable vVarcharArray TARRAY;
select t.varchar2_field
bulk collect into vVarcharArray
from MY_TABLE t
where t.field= vFieldValue;
```

```sql
create or replace type TARRAY is table of varchar2(32767);
```

This query will never throw exceptions `NO_DATA_FOUND`, `TOO_MANY_ROWS`. No exception handling required. Also, the variable `vVarcharArray` will never be `null`

A bug? or I'm wrong?

**Comment by felipebz** [comment]
Hi! I'm sorry for lack of response.

I think you're right, I need to add some exceptions for this rule. :-)
