### ISSUE TITLE
"Always specify the columns in an INSERT statement" should not raise when using a record

### ISSUE THREAD

**Issue by jrx-info** [felipebz/zpa#129]
Hello,

I'm new using this plugin and I first have to say it's very very usefull here !

We very often use records for our insert statements :
example :

```
SUBTYPE R_CMD_SGA IS CMD_SGA%ROWTYPE;

PROCEDURE INS_CMD_SGA(P_REC IN OUT R_CMD_SGA) IS
  BEGIN
    INSERT INTO CMD_SGA
    VALUES
       P_REC;
  END INS_CMD_SGA;
```

I think the error should not be raised in that case.
I don't know how the plugin works, maybe the error should not raise when there is no parenthesis after the "VALUES" keyword ?

Thank you for all the great job you are doing here :)

**Comment by felipebz** [comment]
Hi! Yes, it shouldn't report an error in this situation. Thanks for reporting. :-)
