### ISSUE TITLE
case statement definition incorrect?

### ISSUE THREAD

**Issue by JoopBL** [felipebz/zpa#130]
The case definition in the plsq parser is build as:
`        b.rule(CASE_EXPRESSION).is(
                CASE, b.optional(EXPRESSION),
                b.oneOrMore(WHEN, EXPRESSION, THEN, EXPRESSION),
                b.optional(ELSE, EXPRESSION),
                END);
`
Oracle defines it as:
`[ <<label_name>> ]
CASE { WHEN boolean_expression THEN {statement;} ... }...
[ ELSE {statement;}... ]
END CASE [ label_name ];`

the differenc is the case keyword after the end keyword.
we use mostly the case statement without, but some code contains it. 

some test code:
```sql
create or replace package body
X_U IS
FUNCTION F_I
 RETURN XMLTYPE
 IS
--
  pl_xml_invoic_body xmltype;
begin
  select 
  xmlagg
         ( xmlelement
           ( case
                 when bl_nummer is not null  then 
                 	sx_bvs_edi_xml.f_xmlReference('DQ', bl_nummer)
                 else null
               end case                          
           )
         )
  into   pl_xml_invoic_body
  from   ( 1
         )  ;
  return pl_xml_invoic_body;
end f_iy;

END X_U;`
```

**Comment by felipebz** [comment]
Hi @JoopBL! Thanks for reporting this issue.

There are two different things:
* [CASE expressions](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/CASE-Expressions.html): they end in the "END" keyword
* [CASE statements](https://docs.oracle.com/en/database/oracle/oracle-database/19/lnpls/CASE-statement.html): they end in "END CASE"

This example contains a CASE expression, so Oracle will treat this code as `case (...) end <alias>` where the word "case" is an alias.

I've tested some variations of it, like `select xmlelement("x", case when dummy is not null then 'x' end case) from dual` and I noticed the Oracle compiler accepts it, but in all my tests I got an exception when the code is executed:

```
ORA-19207: scalar parameter CASE of XMLELEMENT cannot have an alias.
*Cause:    The scalar parameter to XMLELEMENT has been qualified with an alias.
*Action:   Remove the AS clause of the scalar element.
```

I didn't really understand how your code is working...  Anyway, if the compiler accepts it, it makes sense to handle this situation here too. ;-)

(I added triple backticks around your example to improve readability)

**Comment by felipebz** [comment]
Oh, I just looked at the [XMLELEMENT documentation](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/XMLELEMENT.html):

```
XMLELEMENT
 ( [ ENTITYESCAPING | NOENTITYESCAPING ]
   [ NAME ]
     { identifier
     | EVALNAME value_expr
     }
   [, XML_attributes_clause ]
   [, value_expr [ [AS] c_alias ]]...
 )
```

> If value_expr is an object type or collection, then the AS clause is mandatory, and Oracle uses the specified c_alias as the enclosing tag.

That explains why my test causes a ORA-19207... I'm testing with a scalar value. Your `sx_bvs_edi_xml.f_xmlReference` probably returns an object type or collection.

**Comment by JoopBL** [comment]
Hello Felipe,

The function returns an xmltype.

Best regards,
Joop Leendertse


Van: Felipe Zorzo <notifications@github.com>
Verzonden: zondag 27 oktober 2019 22:28
Aan: felipebz/zpa <zpa@noreply.github.com>
CC: Leendertse, Joop <J.Leendertse@cb.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [felipebz/zpa] case statement definition incorrect? (#130)


Oh, I just looked at the XMLELEMENT documentation<https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/XMLELEMENT.html>:

XMLELEMENT

 ( [ ENTITYESCAPING | NOENTITYESCAPING ]

   [ NAME ]

     { identifier

     | EVALNAME value_expr

     }

   [, XML_attributes_clause ]

   [, value_expr [ [AS] c_alias ]]...

 )

If value_expr is an object type or collection, then the AS clause is mandatory, and Oracle uses the specified c_alias as the enclosing tag.

That explains why my test causes a ORA-19207... I'm testing with a scalar value. Your sx_bvs_edi_xml.f_xmlReference probably returns an object type or collection.
