### ISSUE TITLE
Not possible integration

### ISSUE THREAD

**Issue by dantemon** [felipebz/zpa#131]
Hi, i have a problem when i add the plugin to the server, i can't start the server and i get this error you have a idea of what could be? 
![Plugin error](https://user-images.githubusercontent.com/44449069/68501525-f7a33280-0223-11ea-9cb3-6d26020a7513.PNG)

**Comment by felipebz** [comment]
Hi @dantemon. Can you please check the logs at logs\web.log? Is there any exception there?

**Comment by dantemon** [comment]
Yeah i have the next exception
![Exception](https://user-images.githubusercontent.com/44449069/68596105-4ccb8800-0460-11ea-9910-f7b9017741ef.PNG)

**Comment by felipebz** [comment]
Thanks @dantemon. Do you have both "sonar-plsql-open-plugin-2.3.0.jar" and your custom plugin (e.g. "plsql-custom-rules-1.0-SNAPSHOT.jar") in the `extensions/plugins` directory? It seems you don't have the main plugin ([sonar-plsql-open-plugin](https://github.com/felipebz/zpa/releases/tag/2.3.0))...

I just tested here and SonarQube 7.7 developer edition starts correctly with my plugin:
![image](https://user-images.githubusercontent.com/13829/68633286-0f9ede80-04d0-11ea-9f75-422f7f43de27.png)

**Comment by dantemon** [comment]
Oh i think i miss the "sonar-plsql-open-plugin-2.3.0.jar" i didnt know i have to put it there, thanks a lot, i have another Question when i use the same code you use on the example i get a different AST, you think this could affect the plugin? or it doesnt matter that much, i hust think its weird this happen
![AST](https://user-images.githubusercontent.com/44449069/68681403-f7a77900-0528-11ea-8089-eb6dde9049c1.PNG)

**Comment by dantemon** [comment]
And another Question, it's possible to make both scan the same file extension or i have to forcefully decide which one have to scan it
![double extension](https://user-images.githubusercontent.com/44449069/68684413-0f353080-052e-11ea-95d6-a2721bf63a0a.PNG)

**Comment by felipebz** [comment]
> when i use the same code you use on the example i get a different AST, you think this could affect the plugin?

No, it doesn't. My plugin is completely independent from SonarPLSQL (the commercial offering from SonarSource) and, being so, it doesn't generate the same AST.

> it's possible to make both scan the same file extension or i have to forcefully decide which one have to scan it

Unfortunately, SonarQube doesn't allow that two different plugins analyze the same file. For now you'll have to choose between the plugins setting the properties `sonar.plsql.file.suffixes` (for SonarPLSQL) or `sonar.zpa.file.suffixes` (for ZPA) accordingly.

In the next months I intend to release the [zpa-cli](https://github.com/felipebz/zpa-cli) to enable this scenario. It'll be possible to analyze the same file with both SonarPLSQL and ZPA without having to install my plugin in the SonarQube server.

**Comment by dantemon** [comment]
Oh i see thanks a lot for your help i appreciate it

**Comment by dantemon** [comment]
> 
> 
> > when i use the same code you use on the example i get a different AST, you think this could affect the plugin?
> 
> No, it doesn't. My plugin is completely independent from SonarPLSQL (the commercial offering from SonarSource) and, being so, it doesn't generate the same AST.
> 
> > it's possible to make both scan the same file extension or i have to forcefully decide which one have to scan it
> 
> Unfortunately, SonarQube doesn't allow that two different plugins analyze the same file. For now you'll have to choose between the plugins setting the properties `sonar.plsql.file.suffixes` (for SonarPLSQL) or `sonar.zpa.file.suffixes` (for ZPA) accordingly.
> 
> In the next months I intend to release the [zpa-cli](https://github.com/felipebz/zpa-cli) to enable this scenario. It'll be possible to analyze the same file with both SonarPLSQL and ZPA without having to install my plugin in the SonarQube server.

One last question when you think this new feature could be release, do you have some date on mind?

**Comment by felipebz** [comment]
To be honest, I don't have any date in mind. Maybe January 2020.

**Comment by dantemon** [comment]
I see, thanks a lot for all your help
