### ISSUE TITLE
Support for Gradle ? 

### ISSUE THREAD

**Issue by Veranicus** [felipebz/zpa#136]
Hello, this plugin doesn't require any other syntax in running bash command than typical sonar scanner ? Or do you need to actually have https://mvnrepository.com/artifact/org.sonar.plsqlopen/sonar-plsql-open-plugin/2.4.0 as a dependency in your project and then you just run the task associated with this gradle plugin which generates report which is then used thanks to your sonar plugin inside sonarqube server and reports are shown that way ?  Thanks for your clarification.

**Comment by felipebz** [comment]
Hi. Sorry for not getting back to you sooner. You don't need to add the plugin as a dependency of your project, just follow the standard [SonaScanner for Gradle instructions](https://docs.sonarqube.org/latest/analysis/scan/sonarscanner-for-gradle/).
