### ISSUE TITLE
creating a rule for all reserved words

### ISSUE THREAD

**Issue by tplazaro** [felipebz/zpa#144]
Hi - is there a way to parse all reserved words and create a custom rule out of it? For example, all keywords should be in uppercase. Thank you!

**Comment by l0wlik34G6** [comment]
What we did once was creating a list of all the reserved words and checking if the current token is in this list. If so, add the issue.
But I don't know if there is a better way.

It might depend on your version, but we took the list from the oracle doc: https://docs.oracle.com/en/database/oracle/oracle-database/21/lnpls/plsql-reserved-words-keywords.html

**Comment by tplazaro** [comment]
thanks for the suggestion!
