### ISSUE TITLE
Confusion!!!

### ISSUE THREAD

**Issue by alperensayar** [felipebz/zpa#170]
Hello,

I download and see PLSQL on marketplace
![Ekran Resmi 2023-08-05 19 21 49](https://github.com/felipebz/zpa/assets/56897887/e12df649-4fa1-4ea0-a2e2-ec1829c5be64)

after that I created a folder plsqls and then also create something.sql file in this folder.
![Ekran Resmi 2023-08-05 19 23 30](https://github.com/felipebz/zpa/assets/56897887/625e2eed-9b03-42d6-823b-ff24d6d73f63)

After that from sonarqube I select from locally choose others.
and start analyze.

Now its my code 
![Ekran Resmi 2023-08-05 19 24 53](https://github.com/felipebz/zpa/assets/56897887/8c6d2a78-f684-4b2e-b6b5-7dd621f3029f)
after that analyze it say report from sonar qube
![Ekran Resmi 2023-08-05 19 25 24](https://github.com/felipebz/zpa/assets/56897887/d0ae921a-4aeb-4c8d-8e2c-db3c55d5b94c)
![Ekran Resmi 2023-08-05 19 25 40](https://github.com/felipebz/zpa/assets/56897887/4ae517e9-bec6-4a3e-8560-58292a49a95f)
![Ekran Resmi 2023-08-05 19 25 55](https://github.com/felipebz/zpa/as
![Ekran Resmi 2023-08-05 19 26 20](https://github.com/felipebz/zpa/assets/56897887/dfabdd84-dcce-4be6-9a3e-27bae78c7589)
sets/56897887/9854ce63-6bfe-4fbd-a7f1-3020d424148f)
![Ekran Resmi 2023-08-05 19 26 51](https://github.com/felipebz/zpa/assets/56897887/a2e31bbf-0264-463c-bb32-bbc24104ca32)

Can you help me? 

Thanks for now.

**Comment by felipebz** [comment]
Hi there,

Thanks for reaching out! I'd be happy to help, but I need a bit more information to understand what you're experiencing. Can you please provide more details about the issue you're having or what are your expectations exactly?

Once I have more information, I'll be able to give you a more specific answer.
