### ISSUE TITLE
False-positive "Specify the columns in this INSERT." when using ROWTYPE

### ISSUE THREAD

**Issue by rstribrn** [felipebz/zpa#176]
False-positive "Specify the columns in this INSERT." when using ROWTYPE:

p_row          IN  mytable%ROWTYPE

INSERT INTO mytable
  VALUES p_row
  RETURNING ID INTO p_id;

Maybe parsing should detect "missing brackets" behind VALUES, and consider it a rowtype variable (search for it)????

**Comment by felipebz** [comment]
Hi,

Thanks for reporting this issue. Actually the rule already checks for ROWTYPE variables, but in this case it was checking the wrong variable ("p_id" from the RETURNING INTO clase, instead of "p_row" from the VALUES clause).

**Comment by rstribrn** [comment]
Thank you! That was really fast.
