### ISSUE TITLE
Rule 'VariableHiding' - exception entries not included 

### ISSUE THREAD

**Issue by khirzer** [felipebz/zpa#180]
Hi!

The rule 'VariableHiding' does not create an issue for user-defined exception 'customExc' (see code below).
An issue for variable 'numberVar' is created.

```
create or replace package body TestPackage is

procedure test is

  numberVar number;
  customExc exception;

  procedure testNested is
    numberVar number;
    customExc exception;
  begin
    null;
  end testNested;

begin
  null;
end test;

END TestPackage;
```

Used zpa version: 3.2.0

In zpa version 3.1.1 the rule works as expected.

Could you please take a look at this? Thank you very much!

**Comment by felipebz** [comment]
Hi @khirzer,

Thank you for reporting this issue. It was caused by a change in the way we handle user-defined exceptions in version 3.2.0+.

**Comment by felipebz** [comment]
Hi @khirzer,

Thank you for reporting this issue. I found that it was caused by a change in the way we handle user-defined exceptions in version 3.2.0+.
