### ISSUE TITLE
A few leagal sql statements that fail

### ISSUE THREAD

**Issue by dados** [felipebz/zpa#181]
select
  'hello'
, 'oracle.dbs'
, 'jackie''s raincoat'
, '09-mar-98'
, ''
, ''''
, q'!name like '%dbms_%%'!'
, q'<'so,' she said, 'it's finished.'>'
, q'{select * from employees where last_name = 'smith'}'
, q'"name like '['"'
, q'#name like #smth #'
, q''name like 'smth ''
, q'(name like )) )'
, n'nchar literal'
from dual
/
select :1, :X, :1 + 1, 1 + :2 from A where A=:3 and b= : 4 and c= :5and :A = :b
/
select * from dual where 1 < > 2 and 1 ! = 2 and 1 ^ /*aaa */
-- testing
= 2

**Comment by felipebz** [comment]
Hi,

Thank you for reporting these issues!

**Comment by felipebz** [comment]
Hi,

The next release will parse all the examples correctly:

![image](https://github.com/felipebz/zpa/assets/13829/a5c1c97f-dd74-4c9f-83a5-6fde24542579)

**Comment by dados** [comment]
Thank you
