### ISSUE TITLE
Simple SQL Injections not detected

### ISSUE THREAD

**Issue by isgroup-srl** [felipebz/zpa#96]
The plugin does not detect easy to spot SQL Injections as the following:

```
CREATE OR REPLACE PROCEDURE putlineDesc ( vname IN VARCHAR2 ) AS
   TYPE rcursor IS REF CURSOR;
   cur rcursor;
   vdesc VARCHAR2(1000);
   vsql VARCHAR2(4000);
BEGIN
   vsql := 'SELECT description FROM products WHERE name=''' || vname || '''';
   OPEN cur FOR vsql;
   LOOP
      FETCH cur INTO vdesc
      EXIT WHEN cur%NOTFOUND;
      dbms_output.put_line(vdesc);
   END LOOP;
   CLOSE cur;
END;
```

`vname` is the vulnerable input.

Instead the project result as clear:

![screenshot from 2018-12-13 14-40-00](https://user-images.githubusercontent.com/3922436/49942229-05054f00-fee5-11e8-9f29-709aa47ac086.png)

**Comment by felipebz** [comment]
Yes, this was expected since there are no rules checking for SQL injection yet.

**Comment by isgroup-srl** [comment]
@felipebz it would be super cool!

**Comment by term73** [comment]
@felipebz - that would make life much easier ...
